version: '3.8'

services:
  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_service_vps
    ports:
      - "5678:5678"
    environment:
      - N8N_BLOCK_PRIVATE_NETWORKS=false
      - N8N_HOST=n8n.vps.hungaroconsultoria.com.br
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_EDITOR_BASE_URL=https://n8n.vps.hungaroconsultoria.com.br
      - WEBHOOK_URL=https://webhook.vps.hungaroconsultoria.com.br/
      - GENERIC_TIMEZONE=America/Sao_Paulo # <-- Ajuste para seu fuso horário
      - NODE_FUNCTION_ALLOW_EXTERNAL=luxon
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_service_vps
    #command: redis-server --save 20 1 --loglevel warning
    command: redis-server --requirepass default
    environment:
      REDIS_USER: default
      REDIS_PASSWORD: default
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network
    
  # --- NOVO SERVIÇO: VISUALIZADOR PARA O REDIS ---
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander_service_vps
    environment:
      # Aponta para o serviço Redis e informa a senha
      - REDIS_HOSTS=redis.vps.hungaroconsultoria.com.br/:redis_service_vps:6379:0:default
    ports:
      - "8081:8081" # Expõe a interface web na porta 8081
    depends_on:
      - redis
    networks:
      - app-network
      
  # --- NOVO SERVIÇO: BANCO DE DADOS POSTGRESQL ---
  postgres:
    image: postgres:14-alpine # Imagem leve e estável do Postgres
    container_name: postgres_service_vps
    environment:
      #- POSTGRES_USER=gabriel #não colocar isso na versão que sobe
      - POSTGRES_PASSWORD=admin # Mude para uma senha segura
      - POSTGRES_DB=evolution
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # Volume para persistir os dados
    networks:
      - app-network
    # Expor a porta é opcional, útil para debug com um cliente de DB como o DBeaver
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gabriel -d evolution"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  waha:
    image: devlikeapro/waha:latest # Imagem recomendada do Waha
    container_name: waha_service_vps
    ports:
      - "3000:3000"
    environment:
      # Conecta o Waha ao Redis para salvar a sessão
      - WHA_ENGINE_SESSION_STORAGE=redis
      - WHA_REDIS_URL=redis://:default@redis_service_vps:6379 # URL correta com senha
      - WHATSAPP_HOOK_URL=https://waha.vps.hungaroconsultoria.com.br/webhook/webhookagendamento
      - WHATSAPP_HOOK_EVENTS=message
    depends_on:
      - redis
    networks:
      - app-network
      
# --- NOVO SERVIÇO: EVOLUTION API ---
  evolution_api:
    image: atendai/evolution-api:latest # Imagem oficial da Evolution API
    container_name: evolution_api_service_vps
    ports:
      - 8080:8080 # Porta padrão da Evolution API
      
    environment:
      - SERVER_URL=https://evolutionapi.vps.hungaroconsultoria.com.br
      # --- Conexão com o Banco de Dados Principal (PostgreSQL ) ---
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://gabriel:admin@postgres_service_vps:5432/evolution
      # --- NOVA SEÇÃO: Conexão com o Cache e Fila (Redis) ---
      - CACHE_REDIS_ENABLED=true
      #- CACHE_TYPE=redis
      - CACHE_REDIS_URI=redis://:default@redis_service_vps:6379 # URL correta com senha
      # --- Outras Configurações ---
      - WEBHOOK_GLOBAL_URL=https://evolutionapi.vps.hungaroconsultoria.com.br/webhook/webhookagendamento # Webhook específico
      - WEBHOOK_GLOBAL_EVENTS=MESSAGE_RECEIVED,CONNECTION_STATUS
      - AUTHENTICATION_API_KEY=jTUGJBACqMHht7haSTK6dE66zOv6lsetaebRZbtZSV7aVaZQotuocpMIpxRPCS3G9LI9lLuIlKItyoc2RKDvgMhPiIFA4FKonftFz7LbnAyCotITK21czwkInJLLkqlm # Defina uma chave de API segura
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1024876920
    volumes:
      - ./evolution_instances:/app/instances # Volume para persistir as sessões
    depends_on:
      postgres: # <-- Forma longa
        condition: service_healthy # <-- A instrução crucial
      redis:
        condition: service_started
      n8n:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  n8n_data:
  redis_data:
  waha_data:
  evolution_instances: # Novo volume para Evolution
  mcp_data:       # Novo volume para MCP